using System.ComponentModel.Composition;
using XrmToolBox.Extensibility;
using XrmToolBox.Extensibility.Interfaces;

namespace VerseOps.XrmToolBox
{
    /// <summary>
    /// MEF entry point. XrmToolBox discovers plugins by composing every
    /// <see cref="IXrmToolBoxPlugin"/> export it finds under
    /// <c>%appdata%\MscrmTools\XrmToolBox\Plugins\</c>. The ExportMetadata
    /// values populate the plugin tile on the XrmToolBox landing page.
    /// </summary>
    [Export(typeof(IXrmToolBoxPlugin)),
     ExportMetadata("Name", "VerseOps API Explorer"),
     ExportMetadata("Description", "Power Platform PPAC/BAP REST API explorer — same catalog as the standalone VerseOps app, embedded in XrmToolBox."),
     // Brand: VerseOps Fluent blue gradient mark. Matches docs/brand/verseops-mark.svg.
     ExportMetadata("BackgroundColor", "#0078D4"),
     ExportMetadata("PrimaryFontColor", "White"),
     ExportMetadata("SecondaryFontColor", "Gainsboro"),
     // Base64 PNG blobs live in VerseOpsBrand.g.cs (generated by
     // tools/build-brand-assets.ps1 from docs/brand/verseops-mark-32.png
     // and docs/brand/verseops-mark-80.png).
     ExportMetadata("SmallImageBase64", VerseOpsBrand.SmallImageBase64),
     ExportMetadata("BigImageBase64",   VerseOpsBrand.BigImageBase64)]
    public class VerseOpsPluginFactory : PluginBase, IGitHubPlugin, IHelpPlugin
    {
        // IGitHubPlugin — wires the "View on GitHub" / source-repo link on the
        // plugin tile and About dialog. UserName + RepositoryName combine into
        // https://github.com/{UserName}/{RepositoryName}.
        public string UserName => "SweetsNSavories";
        public string RepositoryName => "VerseOps";

        // IHelpPlugin — wires the in-host "?" button on the plugin tile to the
        // plugin-specific README rather than the WPF-app pitch.
        public string HelpUrl => "https://github.com/SweetsNSavories/VerseOps/blob/main/VerseOps.XrmToolBox/README.md";

        public override IXrmToolBoxPluginControl GetControl()
        {
            return new VerseOpsPluginControl();
        }
    }

    /// <summary>
    /// Brand-asset constants for the XrmToolBox plugin tile. The base64
    /// PNG payloads are in <c>VerseOpsBrand.g.cs</c>, generated by
    /// <c>tools/build-brand-assets.ps1</c>. Declared partial here so the
    /// type is discoverable in source control.
    /// </summary>
    internal static partial class VerseOpsBrand
    {
    }
}
