# Redacts sensitive cells in a captured VerseOps screenshot by applying heavy
# pixelation to fixed pixel rectangles. Used to scrub:
#   - Env names (column "Name")
#   - Security group GUID prefixes (column "Security Group")
#   - Instance URLs (column "Instance URL")
#   - Env IDs (column "Env ID")
# without losing the cockpit layout, KPI tiles, or storage metrics that make
# the screenshot worth showing.
#
# Coordinates are tuned for a 1400x820 capture of the maximized window when
# the user runs at 100% DPI and the grid layout matches the InventoryView.xaml
# version at the time of writing. If columns ever move, re-measure from
# 01-overview.png.
param(
    [string]$InputPath  = (Join-Path $PSScriptRoot '..\docs\blog\images\01-overview-raw.png'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\docs\blog\images\01-overview.png'),
    [int]$BlockSize     = 14
)

Add-Type -AssemblyName System.Drawing

# y-range of the grid BODY (just under header strip, just above footer strip).
$rowsTop    = 315
$rowsBottom = 795

# x-ranges per column (left,right) — measured from 01-overview-raw.png.
# Widened generously to catch GUID-prefix bleed on the left edge of each cell.
$cols = @(
    @{ Name = 'Name';            X1 =   12; X2 = 220 }
    @{ Name = 'SecurityGroup';   X1 =  475; X2 =  590 }
    @{ Name = 'InstanceUrl';     X1 =  855; X2 = 1030 }
    @{ Name = 'EnvId';           X1 = 1095; X2 = 1320 }
)

$bmp = [System.Drawing.Bitmap]::FromFile($InputPath)
$out = New-Object System.Drawing.Bitmap($bmp.Width, $bmp.Height)
$g = [System.Drawing.Graphics]::FromImage($out)
try {
    $g.DrawImage($bmp, 0, 0)
    $g.SmoothingMode      = [System.Drawing.Drawing2D.SmoothingMode]::None
    $g.InterpolationMode  = [System.Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
    $g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::Half

    foreach ($c in $cols) {
        $left   = [Math]::Max(0, $c.X1)
        $right  = [Math]::Min($out.Width, $c.X2)
        $width  = $right - $left
        $height = $rowsBottom - $rowsTop
        if ($width -le 0 -or $height -le 0) { continue }

        # Pixelate by downsampling the rectangle to (width/block, height/block)
        # and re-drawing at full size with NearestNeighbor — produces big
        # mosaic blocks that destroy any text-recovery via super-resolution.
        $smallW = [Math]::Max(1, [int]($width  / $BlockSize))
        $smallH = [Math]::Max(1, [int]($height / $BlockSize))

        $small = New-Object System.Drawing.Bitmap($smallW, $smallH)
        $sg = [System.Drawing.Graphics]::FromImage($small)
        try {
            $sg.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBilinear
            $sg.DrawImage($bmp,
                (New-Object System.Drawing.Rectangle(0, 0, $smallW, $smallH)),
                $left, $rowsTop, $width, $height,
                [System.Drawing.GraphicsUnit]::Pixel)
        } finally { $sg.Dispose() }

        $g.DrawImage($small,
            (New-Object System.Drawing.Rectangle($left, $rowsTop, $width, $height)),
            0, 0, $smallW, $smallH,
            [System.Drawing.GraphicsUnit]::Pixel)

        $small.Dispose()
    }
} finally {
    $g.Dispose()
}

# Replace the input file in-place; the original will be regenerated by the
# capture script if needed.
$bmp.Dispose()
$out.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
$out.Dispose()
Write-Host "Redacted $OutputPath"
